### ISSUE TITLE
Where can I find Image data?

### ISSUE THREAD

**Issue by emelpolaris** [wendellswa06/alchemydata#1]
I'm gonna train the sdxl model (stabilityai/stable-diffusion-xl-base-1.0) with your database. Here are detailed prompts but couldn't find image data.

**Comment by wendellswa06** [comment]
understood. you can use coco dataset. upscaling is needed to train the sdxl model.

**Comment by emelpolaris** [comment]
thank you

**Comment by wendellswa06** [comment]
no problem
